env:
  es6: true

extends:
  - airbnb-base
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "babel-eslint"

parserOptions:
  ecmaVersion: 2018
  sourceType: module

settings:
  import/resolver:
    babel-module: {}

plugins:
  - jest
  - prettier

rules: {
  "no-console": "off",
  "prettier/prettier": "error",
  "import/prefer-default-export": 0
}
