env:
  es6: true

extends:
  - airbnb-base
  - prettier
  - plugin:import/typescript
  - plugin:jest/recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2018
  sourceType: module

plugins:
  - '@typescript-eslint'
  - jest
  - prettier

rules: {
  "no-console": "off",
  "prettier/prettier": "error",
  "import/prefer-default-export": 0
}
