service: user-service
frameworkVersion: ">=1.11.0 <2.0.0"
provider:
  name: aws
  apiKeys:
    - ${self:service}-${opt:stage}-internal
  runtime: nodejs10.x
  region: us-east-1
  versionFunctions: false
  environment:
    STAGE: ${opt:stage}

plugins:
  - serverless-offline

package:
  exclude:
    - .serverless/**
    - .build/**
    - .buildkite/**
    - bin/**
    - coverage/**
    - src/**/*.test.js
    - .editorconfig
    - .env-*
    - .tslint*
    - .envrc
    - .gitignore
    - .node-version
    - .yarnrc
    - "*.sh"
    - package.json
    - yarn.lock
    - README.md
    - webpack.config.js
    - tsconfig.json
    - __mocks__
    - __test__

functions:
  graphql:
    handler: src/graphql/index.handler
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: graphql
          method: post
          cors: true
          private: true
    alarms:
      - name: functionInvocations
        threshold: 3000
    tags:
      FunctionType: graphql_api
